GPU: '3'
datasets_path: /data/zhouxirou/All_Datasets/dataset_CI_syn_Q004_a5000_b1600/dataset_zxr_all_frequency_Q004_beta1600-1-T1000H245W245/30Hz/30Hz_Noisy
gt_path: /data/zhouxirou/All_Datasets/dataset_CI_syn_Q004_a5000_b1600/dataset_zxr_all_frequency_Q004_beta1600-1-T1000H245W245/30Hz/30Hz_GT/clean_30Hz_1000frames.tif
sampling_mode: temporal_mask
mask_ratio: 0.01
mask_min_dist: 3
kappa_mode: fixed
mpgn_kappa: 100.0
checkpoint_every_epochs: 5
validation_every_epochs: 1
trans_order: st
